spring:
  mvc:
    view:
      suffix: .html

logging:
  level:
    org.springframework.web: DEBUG

exchange:
  access-key: 0515a49dfab221e7ab4317ca087a516e
  currencies:
    - KRW
    - JPY
    - PHP